import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ProductProvider} from "@/components/productContext";
import I18nProvider from "@/components/I18nProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "blueJean - client eCommerce",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <ProductProvider>
            <div >
              {children}
            </div>
          </ProductProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
